language: node_js
node_js:
- '6'
deploy:
  provider: heroku
  api_key:
    secure: OzxdgeQqaoKirIuCHTXyW3T7KCZwzVURZZFyEgOVqauG+I+oaB8gP7mnzf5yKyXC1IQzLc8uretlhqjTHoXEldadjoTllOyFaI+O4mhYWuFr0S4vDKpQfLsEeyGdcjoNSX/eD/p9Akjd0uCgLKD68V3Zy1mU+UxTwEERTcmW0H3XvkhZDPemljEEvpkPEzSA9a3YUUKUvZzKIw1dFb7gMzLGLaia9+GyPlD8JqICJWwLUYBcrp/w2iqEu3MXuyGto9LC67gyBgNqbQIO0dzqmLDVvKoBhZhGE3NwofIRh/M7ci4SnJVP7Y8HftU8HUjSvydUvLK6mIYxRfYtfC48Fc9yb5C6bN83iouhJuNhonScW56HD1nVRRfeIMbB1GE1VjqvNU7M3r+gixcaSqe+p4eQZnV/9uIyzBPMugGuqTOuvWJybGpilvusQdz9FRSUn2PFw4wSE8TT+YnX4gl87Q15dF+wiICd+UOEvTuoV1WaVBkeZ6r4SKMMBEz7W7Qxuk2EL3Qij0r/rqCAbIHCkdQhMq3MtRyXpaAr2DUs50IKdsIVxQANwGF7avvKkX0pR/TUlwAHnOeIDxv7mWhFl+4TykSIfVmNJZapu4hu6+y2J8dsjhG6eXxk9nBGnlXQ9xImsK9LkyM6P8pdljIjx7suVrFf9WgA/XPZAU2R3gA=
  app: sb-basic-node-project
  on:
    repo: ubwhole/Basic-Node-Project
