language: node_js
node_js:
- '6'
deploy:
  api_key:
    secure: b2zD1yP76soLKPvkWZjIDgvmogx9rZQIn1u1L4KOq1PpEiVrfnRjmMBBTQiOgHydUBg2mui7bTfzrRrjXS63esIJ7UUanLSp3HkDqzYPxAP9nxdwgJR8UcRaGR85hauLJ53/kwph6RaKVUuHXJtaH+tEI5FdiAAd3VESdo1UALmEQS9BIQZ9sJHe7dwStx7pMAHuraQSQWHsdwMLHVboL1tDnVva9e/m1d07HEo+kzhQnE+pE4SoxZ/NMWeySbFszwv18sUNk0E6hkOU1IjGB/0JFQwgRvm3DRKUnZK5iv6OqUZx57eLOe35WjIO3mI3YhErRDrqyfOG4PzeZtfEyJlWARmqywLLeP6ALUMAGOHyD8zKdftPpiS36gGOd5MleDPl8pmv30E3nd+F8MrxriqgTLJGVTlxNz0XRKjvJEDytFMIKOQUaZ1IYTSLl79FyB4Rt+ZYH0YYH84JwY9l2+rQdGcH5WK6wf47n2SGDqqWRcYQc2wIRX3k/UNYrxkWlgwU6ld5AbdZY2ge/24XCz6GW50sxGmVVj7yr2YdPBlSC1otnemLZp2souDawlbPIdEdWF7o6VbRMG8/ypGm+U/MEdcz/z9ukw7wZhuDsJfXJ6nRY8WRQjd5arPTvecNDAzQXXkqLCGOMrRVUTDnbeV6AsmQG4nWWnMNU5/T0WY=
  app: sb-basic-node-project
